FROM python:3.9.14-slim

RUN pip install --upgrade pip --no-cache-dir && \
        pip install setuptools-rust oss2 requests-toolbelt androguard requests --no-cache-dir

WORKDIR /opt/

COPY cli.py /opt/cli.py

CMD ["python", "cli.py"]

