# Generated by Django 3.2.3 on 2022-04-05 14:52

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20220330_0009'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xsign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='udidsyncdeveloper',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='udidsyncdeveloper',
            name='status',
            field=models.CharField(
                choices=[('DISABLED', '禁用'), ('ENABLED', '启用'), ('PROCESSING', '处理中'), ('INELIGIBLE', '不合格')],
                default='DISABLED', max_length=16, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='appiosdeveloperinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, '疑似被封'), (0, '未激活'), (1, '已激活'), (2, '协议待同意'),
                                                    (3, '维护中'), (4, '证书过期'), (5, '证书丢失'), (6, '设备异常'),
                                                    (99, '状态异常')], default=0, verbose_name='账户状态'),
        ),
        migrations.CreateModel(
            name='AppleSignMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=256, verbose_name='操作功能')),
                ('operate_status',
                 models.SmallIntegerField(choices=[(0, '失败'), (1, '成功')], default=0, verbose_name='状态')),
                ('message', models.TextField(blank=True, default='', verbose_name='操作详细日志')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('app_id',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.apps')),
                ('developerid',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xsign.appiosdeveloperinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                              verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '应用签名操作记录',
                'verbose_name_plural': '应用签名操作记录',
            },
        ),
    ]
