# Generated by Django 3.2.3 on 2022-04-15 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xsign', '0002_auto_20220405_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBlackUDID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udid', models.CharField(max_length=64, unique=True, verbose_name='手动添加设备udid')),
                ('enable', models.BooleanField(default=True, verbose_name='是否生效')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                              verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '设备黑名单',
                'verbose_name_plural': '设备黑名单',
            },
        ),
        migrations.CreateModel(
            name='DeviceAbnormalUDID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_remove', models.BooleanField(default=True, verbose_name='是否自动移除')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('udid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xsign.udidsyncdeveloper',
                                           verbose_name='自动添加设备udid')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                              verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '异常设备信息',
                'verbose_name_plural': '异常设备信息',
            },
        ),
    ]
