# Generated by Django 4.0.8 on 2022-11-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('xsign', '0003_deviceabnormaludid_deviceblackudid'),
    ]

    operations = [
        migrations.AddField(
            model_name='udidsyncdeveloper',
            name='device_class',
            field=models.CharField(
                choices=[('APPLE_WATCH', 'APPLE_WATCH'), ('IPAD', 'IPAD'), ('IPHONE', 'IPHONE'), ('IPOD', 'IPOD'),
                         ('APPLE_TV', 'APPLE_TV'), ('MAC', 'MAC')], default='IPHONE', max_length=16,
                verbose_name='设备类型'),
        ),
    ]
