# Generated by Django 3.0.3 on 2020-05-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appiosdeveloperinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='email address'),
        ),
        migrations.AlterUniqueTogether(
            name='appiosdeveloperinfo',
            unique_together={('user_id', 'email')},
        ),
        migrations.RemoveField(
            model_name='appiosdeveloperinfo',
            name='name',
        ),
    ]
