# Generated by Django 3.0.3 on 2021-05-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaincnameinfo',
            name='is_https',
            field=models.BooleanField(default=False, verbose_name='是否支持HTTPS'),
        ),
    ]
