# Generated by Django 3.2.3 on 2021-06-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='supersign_active',
            field=models.BooleanField(default=True, verbose_name='配置超级签，默认关闭'),
        ),
    ]
