# Generated by Django 3.2.3 on 2021-06-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20210607_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='new_bundle_name',
            field=models.CharField(blank=True, help_text='应用新名称', max_length=64, null=True,
                                   verbose_name='new_bundle_name'),
        ),
    ]
