# Generated by Django 3.2.3 on 2022-02-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20220215_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBundleIdBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(default='*', max_length=64, verbose_name='用户ID,*表示全局')),
                ('bundle_id', models.CharField(blank=True, max_length=64, verbose_name='bundle id')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用该配置项')),
                ('status', models.SmallIntegerField(choices=[(0, '黑名单'), (1, '白名单')], default=1, verbose_name='状态')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '新应用上传黑白名单',
                'verbose_name_plural': '新应用上传黑白名单',
                'unique_together': {('user_uid', 'bundle_id')},
            },
        ),
    ]
