# Generated by Django 3.0.3 on 2021-05-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_domaincnameinfo_is_https'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domaincnameinfo',
            options={'verbose_name': '系统分发域名配置', 'verbose_name_plural': '系统分发域名配置'},
        ),
        migrations.AlterModelOptions(
            name='userdomaininfo',
            options={'verbose_name': '用户分发域名绑定', 'verbose_name_plural': '用户分发域名绑定'},
        ),
        migrations.AlterField(
            model_name='apps',
            name='supersign_type',
            field=models.SmallIntegerField(
                choices=[(0, '普通权限'), (1, '推送权限，请上传adhoc包'), (2, 'network、vpn、推送权限，请上传adhoc包'), (3, '特殊权限')], default=1,
                verbose_name='签名类型'),
        ),
    ]
