# Generated by Django 3.0.3 on 2020-05-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_apptodeveloper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apptodeveloper',
            options={'verbose_name': '应用开发者绑定', 'verbose_name_plural': '应用开发者绑定'},
        ),
        migrations.AlterField(
            model_name='apptodeveloper',
            name='binary_file',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='签名包名称'),
        ),
    ]
