# Generated by Django 3.0.3 on 2020-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200306_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='appreleaseinfo',
            name='icon_url',
            field=models.CharField(blank=True, max_length=128, verbose_name='图标url'),
        ),
        migrations.AlterField(
            model_name='appreleaseinfo',
            name='release_type',
            field=models.SmallIntegerField(choices=[(0, 'android'), (1, 'adhoc'), (2, 'Inhouse'), (3, 'unknown')], default=0, verbose_name='版本类型'),
        ),
    ]
