# Generated by Django 3.2.3 on 2021-07-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_apps_new_bundle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreleaseinfo',
            name='app_version',
            field=models.CharField(blank=True, max_length=64, verbose_name='app版本'),
        ),
        migrations.AlterField(
            model_name='appreleaseinfo',
            name='build_version',
            field=models.CharField(blank=True, max_length=64, verbose_name='build版本'),
        ),
    ]
