# Generated by Django 3.2.3 on 2022-03-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20220326_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thirdwechatuserinfo',
            options={'verbose_name': '微信相关信息', 'verbose_name_plural': '微信相关信息'},
        ),
        migrations.AlterField(
            model_name='thirdwechatuserinfo',
            name='openid',
            field=models.CharField(max_length=64, verbose_name='普通用户的标识，对当前公众号唯一'),
        ),
        migrations.AlterUniqueTogether(
            name='thirdwechatuserinfo',
            unique_together={('user_id', 'openid')},
        ),
    ]
