# Generated by Django 3.2.3 on 2021-09-07 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20210705_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdWeChatUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=64, unique=True, verbose_name='普通用户的标识，对当前公众号唯一')),
                ('nickname', models.CharField(blank=True, max_length=64, verbose_name='昵称')),
                ('sex', models.SmallIntegerField(default=0, help_text='值为1时是男性，值为2时是女性，值为0时是未知', verbose_name='性别')),
                ('subscribe_time', models.BigIntegerField(verbose_name='订阅时间')),
                ('head_img_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='用户头像')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='地址')),
                ('subscribe', models.BooleanField(default=0, verbose_name='是否订阅公众号')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                              verbose_name='用户ID')),
            ],
        ),
    ]
