# Generated by Django 3.0.3 on 2020-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200306_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='name',
        ),
        migrations.AddField(
            model_name='appreleaseinfo',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='应用名称'),
        ),
    ]
