# Generated by Django 3.2.3 on 2021-09-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_thirdwechatuserinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='qq',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.BigIntegerField(db_index=True, help_text='用于手机验证码登录', null=True, verbose_name='手机'),
        ),
    ]
