# Generated by Django 3.2.3 on 2022-07-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220513_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaincnameinfo',
            name='is_enable',
            field=models.BooleanField(default=False, verbose_name='是否启用该解析'),
        ),
        migrations.AlterField(
            model_name='domaincnameinfo',
            name='domain_record',
            field=models.CharField(max_length=128, verbose_name='记录值'),
        ),
        migrations.AddField(
            model_name='domaincnameinfo',
            name='user_ipk',
            field=models.IntegerField(default=0, verbose_name='用户ipk'),
        ),
        migrations.AlterUniqueTogether(
            name='domaincnameinfo',
            unique_together={('user_ipk', 'domain_record')},
        ),
    ]
