# Generated by Django 3.2.3 on 2021-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_auto_20210907_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udidsyncdeveloper',
            name='platform',
        ),
        migrations.AddField(
            model_name='udidsyncdeveloper',
            name='status',
            field=models.BooleanField(default=False, verbose_name='设备在开发者平台状态'),
        ),
    ]
