# Generated by Django 3.0.3 on 2020-03-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200307_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreleaseinfo',
            name='changelog',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='更新日志'),
        ),
    ]
