# Generated by Django 3.0.3 on 2020-05-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_udidsyncdeveloper'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='wxeasytype',
            field=models.BigIntegerField(default=True, verbose_name='微信内简易房屋，避免微信封停'),
        ),
        migrations.AddField(
            model_name='apps',
            name='wxredirect',
            field=models.BigIntegerField(default=True, verbose_name='微信内第三方链接自动跳转'),
        ),
    ]
