# Generated by Django 3.2.3 on 2021-09-15 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_auto_20210909_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appiosdeveloperinfo',
            name='use_number',
        ),
    ]
