# Generated by Django 3.0.3 on 2020-03-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_appreleaseinfo_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'android'), (1, 'ios')], default=0, verbose_name='类型'),
        ),
    ]
