# Generated by Django 3.0.3 on 2020-09-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200520_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='domain_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='下载页面域名'),
        ),
    ]
