# Generated by Django 3.0.3 on 2020-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200922_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='storage_active',
            field=models.BooleanField(default=False, verbose_name='配置存储，默认关闭'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='supersign_active',
            field=models.BooleanField(default=False, verbose_name='配置超级签，默认关闭'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='download_times',
            field=models.IntegerField(default=100, verbose_name='可用下载次数'),
        ),
    ]
