# Generated by Django 3.0.3 on 2020-03-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200307_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='domain_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='count_hits',
            field=models.BigIntegerField(default=0, verbose_name='下载次数'),
        ),
        migrations.DeleteModel(
            name='AppStorage',
        ),
    ]
