# Generated by Django 3.0.3 on 2020-03-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200309_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='head_img',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='qq',
            field=models.BigIntegerField(blank=True, db_index=True, max_length=64, null=True, verbose_name='QQ'),
        ),
    ]
