# Generated by Django 3.0.3 on 2021-01-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_auto_20200925_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='api_token',
            field=models.CharField(default='', max_length=256, verbose_name='api访问密钥'),
        ),
    ]
