# Generated by Django 3.0.3 on 2020-03-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200309_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='all_download_times',
            field=models.IntegerField(default=0, verbose_name='总共下载次数'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='qq',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='QQ'),
        ),
    ]
