# Generated by Django 3.2.3 on 2021-09-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_alter_userdomaininfo_domain_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appudid',
            name='is_download',
            field=models.BooleanField(default=False, verbose_name='描述文件是否已经下载'),
        ),
    ]
