# Generated by Django 3.2.3 on 2021-10-14 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_appudid_is_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdDisplayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_uri', models.CharField(max_length=256, verbose_name='广告跳转地址')),
                ('ad_pic', models.CharField(help_text='像素最高80px', max_length=256, verbose_name='广告图片地址')),
                ('weight', models.IntegerField(default=1, verbose_name='广告展示权重')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述信息')),
                ('is_enable', models.BooleanField(default=False, verbose_name='广告开启状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='广告创建时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                              verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户自定义广告',
                'verbose_name_plural': '用户自定义广告',
            },
        ),
    ]
