# Generated by Django 3.0.3 on 2020-03-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200310_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='head_img',
            field=models.CharField(default='/static/frontend/head_portrait/logo@2x.png', max_length=256, verbose_name='个人头像'),
        ),
    ]
