# Generated by Django 3.2.3 on 2021-10-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0012_useraddisplayinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddisplayinfo',
            name='ad_name',
            field=models.CharField(default='xx', max_length=256, verbose_name='广告名称'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='useraddisplayinfo',
            index=models.Index(fields=['ad_name', 'user_id'], name='api_useradd_ad_name_4ea10e_idx'),
        ),
    ]
