# Generated by Django 3.0.3 on 2021-01-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210127_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='domain_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='专属访问域名'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='wxeasytype',
            field=models.BigIntegerField(default=True, verbose_name='微信内简易模式，避免微信封停'),
        ),
    ]
