# Generated by Django 3.2.3 on 2021-10-14 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_auto_20211014_1617'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraddisplayinfo',
            unique_together={('ad_name', 'user_id')},
        ),
    ]
