# Generated by Django 3.0.3 on 2021-01-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_auto_20210128_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='appiosdeveloperinfo',
            name='auth_type',
            field=models.SmallIntegerField(choices=[(0, 'p8key认证'), (1, '用户名密码认证')], default=0, verbose_name='认证类型'),
        ),
        migrations.AddField(
            model_name='appiosdeveloperinfo',
            name='issuer_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='标识创建认证令牌的发放者'),
        ),
        migrations.AddField(
            model_name='appiosdeveloperinfo',
            name='p8key',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='p8key'),
        ),
        migrations.AddField(
            model_name='appiosdeveloperinfo',
            name='private_key_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='密钥 ID'),
        ),
        migrations.AlterUniqueTogether(
            name='appiosdeveloperinfo',
            unique_together={('user_id', 'issuer_id'), ('user_id', 'email')},
        ),
    ]
