# Generated by Django 3.0.3 on 2020-03-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200323_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='storage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_storage', to='api.AppStorage', verbose_name='存储'),
        ),
    ]
