# Generated by Django 3.0.3 on 2020-03-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userinfo_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='history_release_limit',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='app 历史记录版本'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='all_download_times',
            field=models.BigIntegerField(default=0, verbose_name='总共下载次数'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='head_img',
            field=models.CharField(default='head_img.jpeg', max_length=256, verbose_name='个人头像'),
        ),
    ]
