# Generated by Django 3.0.3 on 2021-01-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0014_auto_20210129_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appiosdeveloperinfo',
            name='p8key',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='p8key'),
        ),
    ]
