# Generated by Django 3.2.3 on 2021-10-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0015_iosdeveloperpublicpoolbill_remoteclientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appudid',
            name='udid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.udidsyncdeveloper',
                                    verbose_name='udid唯一标识'),
        ),
    ]
