# Generated by Django 3.2.3 on 2021-11-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_alter_appudid_udid'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerappid',
            name='profile_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
