# Generated by Django 3.0.3 on 2021-01-31 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_developerappid_developerdevicesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerdevicesid',
            name='udid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UDIDsyncDeveloper',
                                    verbose_name='所消耗的udid'),
        ),
    ]
