# Generated by Django 3.0.3 on 2020-03-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200327_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstorage',
            name='domain_name',
            field=models.CharField(blank=True, help_text='fly-storage.dvcloud.xin,可以自定义端口', max_length=128, null=True, verbose_name='下载域名'),
        ),
        migrations.AddField(
            model_name='appstorage',
            name='is_https',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否支持https'),
        ),
        migrations.AlterField(
            model_name='appstorage',
            name='additionalparameters',
            field=models.TextField(blank=True, help_text='阿里云:{"sts_role_arn":"arn信息","endpoint":""} ', max_length=256, null=True, verbose_name='额外参数'),
        ),
    ]
