# Generated by Django 3.0.3 on 2020-04-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200331_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreleaseinfo',
            name='release_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='release 版本id'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='app_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='apps',
            name='short',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='短链接'),
        ),
    ]
