# Generated by Django 3.0.3 on 2021-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0017_auto_20210131_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='enable_push_vpn',
            field=models.BigIntegerField(default=False, verbose_name='特殊权限（包含network、vpn）'),
        ),
        migrations.AddField(
            model_name='apps',
            name='new_bundle_id',
            field=models.CharField(blank=True, help_text='用与超级签某些因素下修改包名', max_length=64, verbose_name='new_bundle_id'),
        ),
    ]
