# Generated by Django 3.2.3 on 2021-11-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0017_developerappid_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udid', models.CharField(db_index=True, max_length=64, verbose_name='udid唯一标识')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('app_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apps', verbose_name='应用id')),
                ('developerid',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appiosdeveloperinfo',
                                   verbose_name='所使用苹果开发者账户')),
            ],
        ),
    ]
