# Generated by Django 3.0.3 on 2021-03-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0018_auto_20210308_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='enable_push_vpn',
        ),
        migrations.AddField(
            model_name='apps',
            name='supersign_type',
            field=models.SmallIntegerField(choices=[(0, '普通权限'), (1, '特殊权限（包含network、vpn）')], default=0,
                                           verbose_name='签名类型'),
        ),
    ]
