# Generated by Django 3.0.3 on 2020-04-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200407_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
