# Generated by Django 3.2.3 on 2021-11-04 11:18

from django.db import migrations, models

import api.utils.daobase


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0019_iosdeveloperpublicpoolbill_udid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iosdeveloperpublicpoolbill',
            name='udid_info',
        ),
        migrations.AddField(
            model_name='iosdeveloperpublicpoolbill',
            name='product',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='设备udid'),
        ),
        migrations.AddField(
            model_name='iosdeveloperpublicpoolbill',
            name='version',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='设备udid'),
        ),
        migrations.AlterField(
            model_name='appiosdeveloperinfo',
            name='p8key',
            field=api.utils.daobase.AESCharField(max_length=512, verbose_name='p8key'),
        ),
        migrations.AlterField(
            model_name='appstorage',
            name='secret_key',
            field=api.utils.daobase.AESCharField(blank=True, max_length=128, null=True, verbose_name='存储访问secret'),
        ),
    ]
