# Generated by Django 3.0.3 on 2020-04-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200407_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='password',
            field=models.CharField(default='', help_text='默认 没有密码', max_length=32, verbose_name='访问密码'),
        ),
        migrations.AlterField(
            model_name='appreleaseinfo',
            name='binary_url',
            field=models.CharField(blank=True, max_length=128, verbose_name='第三方下载URL'),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
