# Generated by Django 3.0.3 on 2021-03-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0020_auto_20210308_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='supersign_limit_number',
            field=models.IntegerField(default=0, verbose_name='签名使用限额'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='new_bundle_id',
            field=models.CharField(blank=True, help_text='用于超级签某些因素下需要修改包名', max_length=64, null=True,
                                   verbose_name='new_bundle_id'),
        ),
    ]
