# Generated by Django 3.2.3 on 2021-11-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0020_auto_20211104_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppReportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='应用名称')),
                ('bundle_id', models.CharField(blank=True, max_length=64, verbose_name='bundle id')),
                ('remote_addr', models.GenericIPAddressField(verbose_name='远程IP地址')),
                ('report_type',
                 models.SmallIntegerField(choices=[(0, '侵权'), (1, '色情'), (2, '赌博'), (3, '欺诈'), (4, '暴力'), (5, '其他')],
                                          default=5, verbose_name='举报类型')),
                ('report_reason', models.CharField(max_length=512, verbose_name='举报详情')),
                ('email', models.CharField(max_length=64, verbose_name='联系方式')),
                ('username', models.CharField(max_length=64, verbose_name='姓名')),
                ('status', models.SmallIntegerField(choices=[(1, '处理中'), (2, '已经处理')], default=1, verbose_name='处理状态')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('app_id',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.apps',
                                   verbose_name='应用信息')),
            ],
            options={
                'verbose_name': '应用举报信息',
                'verbose_name_plural': '应用举报信息',
            },
        ),
    ]
