# Generated by Django 3.2.3 on 2021-11-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0021_appreportinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='iosdeveloperpublicpoolbill',
            name='app_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.apps',
                                    verbose_name='属于哪个APP'),
        ),
    ]
