# Generated by Django 3.0.3 on 2020-04-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200410_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='isshow',
            field=models.BigIntegerField(default=1, verbose_name='下载页可见'),
        ),
    ]
