# Generated by Django 3.0.3 on 2021-03-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0021_auto_20210308_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreleaseinfo',
            name='distribution_name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='企业签名'),
        ),
    ]
