# Generated by Django 3.0.3 on 2020-04-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_apps_isshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreleaseinfo',
            name='udid',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='ios内测版 udid'),
        ),
    ]
