# Generated by Django 3.2.3 on 2021-11-06 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0022_iosdeveloperpublicpoolbill_app_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appudid',
            name='binary_file',
        ),
    ]
