# Generated by Django 3.0.3 on 2020-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_appreleaseinfo_udid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreleaseinfo',
            name='udid',
            field=models.TextField(blank=True, default='', null=True, verbose_name='ios内测版 udid'),
        ),
        migrations.AlterField(
            model_name='appstorage',
            name='additionalparameters',
            field=models.TextField(blank=True, default=None, help_text='阿里云:{"sts_role_arn":"arn信息","endpoint":""} ', null=True, verbose_name='额外参数'),
        ),
        migrations.AlterField(
            model_name='appstorage',
            name='is_https',
            field=models.BooleanField(default=True, verbose_name='是否支持https'),
        ),
    ]
