# Generated by Django 3.2.3 on 2021-11-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_appudid_binary_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='远程IP地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.SmallIntegerField(choices=[(0, '用户下单'), (1, '后台充值'), (2, '系统赠送')], default=0, verbose_name='订单类型'),
        ),
    ]
