# Generated by Django 3.0.3 on 2021-03-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0023_auto_20210316_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='download_times',
            field=models.PositiveIntegerField(default=0, verbose_name='可用下载次数,需要用户充值'),
        ),
    ]
