# Generated by Django 3.2.3 on 2021-11-16 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0024_auto_20211108_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceQueue',
        ),
    ]
