# Generated by Django 3.0.3 on 2020-04-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200413_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstorage',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
