# Generated by Django 3.0.3 on 2020-04-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_appstorage_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstorage',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
    ]
