# Generated by Django 3.2.3 on 2021-12-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0026_appledevelopertoappuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='appiosdeveloperinfo',
            name='app_limit_number',
            field=models.IntegerField(default=100, verbose_name='可分配应用数，最大160'),
        ),
    ]
