# Generated by Django 3.0.3 on 2020-04-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200414_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='issupersign',
            field=models.BigIntegerField(default=False, verbose_name='是否超级签名包'),
        ),
    ]
