# Generated by Django 3.2.3 on 2021-12-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0027_appiosdeveloperinfo_app_limit_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appiosdeveloperinfo',
            name='is_actived',
        ),
        migrations.AddField(
            model_name='appiosdeveloperinfo',
            name='status',
            field=models.SmallIntegerField(
                choices=[(0, '未激活'), (1, '已激活'), (2, '协议待同意'), (3, '维护中'), (4, '证书过期'), (5, '状态异常')], default=0,
                verbose_name='账户状态'),
        ),
        migrations.AddField(
            model_name='userdomaininfo',
            name='is_https',
            field=models.BooleanField(default=False, verbose_name='是否支持HTTPS'),
        ),
        migrations.AddField(
            model_name='userdomaininfo',
            name='weight',
            field=models.IntegerField(default=10, verbose_name='下载页域名展示权重'),
        ),
    ]
