# Generated by Django 3.0.3 on 2021-03-29 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0027_auto_20210329_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='订单创建时间'),
            preserve_default=False,
        ),
    ]
