# Generated by Django 3.0.3 on 2020-04-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_appudid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appudid',
            name='iccid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='型号'),
        ),
        migrations.AddField(
            model_name='appudid',
            name='imei',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='appudid',
            name='product',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='appudid',
            name='serial',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='appudid',
            name='version',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='型号'),
        ),
    ]
