# Generated by Django 3.0.3 on 2021-03-29 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0028_order_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
