# Generated by Django 3.0.3 on 2020-04-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200416_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='appudid',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
