# Generated by Django 3.0.3 on 2021-03-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0029_remove_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_download_gift_times',
            field=models.BigIntegerField(default=0, verbose_name='实际赠送的数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='actual_download_times',
            field=models.BigIntegerField(default=0, verbose_name='实际购买的数量'),
        ),
    ]
