# Generated by Django 3.2.3 on 2022-02-03 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0029_auto_20220102_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iosdeveloperpublicpoolbill',
            options={'verbose_name': '设备消耗账单', 'verbose_name_plural': '设备消耗账单'},
        ),
        migrations.RemoveField(
            model_name='iosdeveloperpublicpoolbill',
            name='action',
        ),
        migrations.RemoveField(
            model_name='iosdeveloperpublicpoolbill',
            name='to_user_id',
        ),
        migrations.AlterField(
            model_name='iosdeveloperpublicpoolbill',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='用户ID'),
        ),
        migrations.CreateModel(
            name='IosDeveloperBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '失效'), (1, '撤回'), (2, '转账')], default=0,
                                                    help_text='0 失效 1 撤回 2 转账', verbose_name='状态')),
                ('number', models.IntegerField(default=1, verbose_name='设备数量')),
                ('description', models.CharField(blank=True, default='', max_length=128, verbose_name='操作描述')),
                ('remote_addr', models.GenericIPAddressField(verbose_name='远程IP地址')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('to_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='to_user_id', to=settings.AUTH_USER_MODEL,
                                                 verbose_name='用户ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_user_id',
                                              to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '设备划转账单',
                'verbose_name_plural': '设备划转账单',
            },
        ),
    ]
