# Generated by Django 3.2.3 on 2022-02-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0030_auto_20220203_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='iosdeveloperbill',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='iosdeveloperbill',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '失效'), (1, '已撤回'), (2, '成功')], default=0,
                                           help_text='0 失效 1 撤回 2 转账', verbose_name='状态'),
        ),
    ]
