# Generated by Django 3.0.3 on 2021-04-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0031_auto_20210407_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationinfo',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '国徽面照片'), (1, '人像面照片'), (2, '手持身份证照片')], default=0,
                                           verbose_name='图像类型'),
            preserve_default=False,
        ),
    ]
