# Generated by Django 3.0.3 on 2020-04-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_appiosdeveloperinfo_appsupersignusedinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appudid',
            name='binary_file',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='签名包名称'),
        ),
        migrations.AlterField(
            model_name='appiosdeveloperinfo',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='开发者标识'),
        ),
    ]
