# Generated by Django 3.0.3 on 2021-04-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0032_certificationinfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationinfo',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '未知'), (1, '国徽面照片'), (2, '人像面照片'), (3, '手持身份证照片')], default=0,
                                           verbose_name='图像类型'),
        ),
    ]
