# Generated by Django 3.2.3 on 2022-02-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0032_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='appiosdeveloperinfo',
            name='auto_check',
            field=models.BooleanField(default=False, verbose_name='是否自动检测开发者状态'),
        ),
    ]
