# Generated by Django 3.0.3 on 2021-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0033_auto_20210407_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertificationinfo',
            name='msg',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='备注'),
        ),
    ]
