# Generated by Django 3.0.3 on 2020-04-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200425_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='appiosdeveloperinfo',
            name='certid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='超级签名自动创建证书ID'),
        ),
    ]
