# Generated by Django 3.0.3 on 2021-04-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0034_usercertificationinfo_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertificationinfo',
            name='reviewed_time',
            field=models.DateTimeField(default='2021-04-08 16:28:28.142887', verbose_name='审核时间'),
            preserve_default=False,
        ),
    ]
