# Generated by Django 3.2.3 on 2022-02-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0034_auto_20220208_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='是否启用该配置项'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(max_length=128, unique=True, verbose_name='配置名称'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.TextField(max_length=10240, verbose_name='配置值'),
        ),
    ]
