# Generated by Django 3.0.3 on 2021-04-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210409_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '封禁'), (2, '违规')], default=0, verbose_name='应用状态'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='isshow',
            field=models.BooleanField(default=True, verbose_name='下载页可见'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='issupersign',
            field=models.BooleanField(default=False, verbose_name='是否超级签名包'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='wxeasytype',
            field=models.BooleanField(default=True, verbose_name='微信内简易模式，避免微信封停'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='wxredirect',
            field=models.BooleanField(default=True, verbose_name='微信内第三方链接自动跳转'),
        ),
    ]
