# Generated by Django 3.0.3 on 2021-04-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20210412_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '封禁'), (1, '正常'), (2, '违规')], default=1, verbose_name='应用状态'),
        ),
    ]
