# Generated by Django 3.0.3 on 2021-04-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210412_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='password',
            field=models.CharField(blank=True, help_text='默认 没有密码', max_length=32, verbose_name='访问密码'),
        ),
    ]
