# Generated by Django 3.0.3 on 2021-04-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0039_auto_20210412_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertificationinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, '待认证'), (0, '认证中'), (1, '认证成功'), (2, '认证失败')], default=0,
                                           verbose_name='审核状态'),
        ),
    ]
