# Generated by Django 3.0.3 on 2021-04-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0040_auto_20210413_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(
                choices=[(0, '交易成功'), (1, '待支付'), (2, '订单已创建'), (3, '退费申请中'), (4, '已退费'), (5, '主动取消'), (6, '超时取消')],
                verbose_name='状态'),
        ),
    ]
