# Generated by Django 3.0.3 on 2021-04-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0042_order_payment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appstorage',
            name='additionalparameters',
        ),
        migrations.AddField(
            model_name='appstorage',
            name='cnd_auth_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='阿里云cnd_auth_key'),
        ),
        migrations.AddField(
            model_name='appstorage',
            name='download_auth_type',
            field=models.SmallIntegerField(
                choices=[(1, 'OSS模式： 需要把OSS权限开启私有模式'), (2, 'CDN模式： 请先配置好阿里云CDN，开启阿里云OSS私有Bucket回源，将使用鉴权A方式')],
                default=1, verbose_name='阿里云下载授权方式'),
        ),
        migrations.AddField(
            model_name='appstorage',
            name='endpoint',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='阿里云endpoint'),
        ),
        migrations.AddField(
            model_name='appstorage',
            name='sts_role_arn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='阿里云sts_role_arn'),
        ),
        migrations.AlterField(
            model_name='usercertificationinfo',
            name='addr',
            field=models.CharField(max_length=128, verbose_name='居住地址'),
        ),
        migrations.AlterField(
            model_name='usercertificationinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, '待认证'), (0, '认证中'), (1, '认证成功'), (2, '认证失败')], default=0,
                                           verbose_name='认证状态'),
        ),
    ]
