# Generated by Django 3.0.3 on 2021-04-22 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0043_auto_20210420_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='account',
            new_name='user_id',
        ),
    ]
