# Generated by Django 3.0.3 on 2021-04-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0044_auto_20210422_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertificationinfo',
            name='card',
            field=models.CharField(max_length=128, unique=True, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='usercertificationinfo',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='手机号码'),
        ),
    ]
