# Generated by Django 3.0.3 on 2021-04-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0045_auto_20210423_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertificationinfo',
            name='reviewed_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='审核时间'),
        ),
    ]
