# Generated by Django 3.0.3 on 2021-05-19 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0047_domaincnameinfo_userdomaininfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdomaininfo',
            unique_together=set(),
        ),
    ]
