# Generated by Django 3.0.3 on 2021-05-19 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0048_auto_20210519_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='domain_name',
        ),
    ]
