# Generated by Django 3.0.3 on 2021-05-19 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0050_userdomaininfo_app_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='domain_name',
        ),
    ]
